// @ts-check

import eslint from '@eslint/js';
import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

export default defineConfig(
	{
		ignores: [
			'.wrangler/**',
			'dist/**',
			'node_modules/**',
			'**/*.min.js',
			'coverage/**',
			// Autogenerated by Cloudflare / tooling; exclude from linting
			'worker-configuration.d.ts',
		],
	},
	eslint.configs.recommended,
	tseslint.configs.recommendedTypeChecked,
	tseslint.configs.stylisticTypeChecked,
	{
		languageOptions: {
			parserOptions: {
				projectService: {
					allowDefaultProject: ['*.mjs', '*.js', '*.config.*'],
				},
				tsconfigRootDir: dirname(fileURLToPath(import.meta.url)),
			},
		},
	},
	{
		files: ['**/*.js', '**/*.mjs', '*.config.*'],
		extends: [tseslint.configs.disableTypeChecked],
	}
);
